# Generated by Django 4.2.16 on 2024-10-26 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.IntegerField(blank=True, null=True)),
                ("content", models.TextField()),
                ("writter_uni", models.CharField(blank=True, max_length=50, null=True)),
                ("likes", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Comment2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("writter_uni", models.CharField(blank=True, max_length=50, null=True)),
                ("likes", models.IntegerField(default=0)),
                (
                    "comment1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comment_app.comment1",
                    ),
                ),
            ],
        ),
    ]
